mainSections:
  - post
  - notes
  - project
featuredImageField: image
rssFullContent: true
favicon: dorito.ico # e.g.: favicon placed in `static/favicon.ico` of your site folder, then set this field to `/favicon.ico` (`/` is necessary)

footer:
  since: 2023
  customText: By MJ Sabit

dateFormat:
  published: Jan 02, 2006
  lastUpdated: Jan 02, 2006

sidebar:
  subtitle: pachi pachi pachi pachi
  avatar:
    enabled: true
    local: true
    src: img/seyLu.png

article:
  math: false
  toc: true
  readingTime: true
  license:
    enabled: true
    default: Licensed under CC BY-NC-SA 4.0

comments:
  enabled: true
  provider: giscus

  giscus:
    repo: seyLu/blog
    repoID: R_kgDOKY_jRQ
    category: General
    categoryID: DIC_kwDOKY_jRc4CZucH
    mapping: pathName
    reactionsEnabled: 1
    emitMetadata: 0
    lightTheme: light
    darkTheme: transparent_dark

widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    - type: categories
      params:
        limit: 10
    - type: tag-cloud
      params:
        limit: 10
  page:
    - type: toc

opengraph:
  twitter:
    # Your Twitter username
    site:

    # Available values: summary, summary_large_image
    card: summary_large_image

defaultImage:
  opengraph:
    enabled: false
    local: false
    src:

colorScheme:
  # Display toggle
  toggle: true

  # Available values: auto, light, dark
  default: dark

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true
